### 1. Numpy 

In [2]:
import numpy as np

### Numpy Arrays

In [3]:
np1 = np.array([0,1,2,3,4,5,6,7,8,9])
print(np1)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# Get Dimention
np1.ndim

1

In [ ]:
# Get type
a = np.array([1,2,3,4], dtype='int16')
a.dtype

dtype('int16')

In [9]:
# Get Size
a.itemsize


2

In [10]:
# total size
a.nbytes

8

In [3]:
print(np1.shape)

(10,)


In [5]:
# Range
np2 = np.arange(10)
print(np2)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
# Step
np3 = np.arange(0, 10, 2)
print(np3)

[0 2 4 6 8]


In [7]:
# Zeros
np4 = np.zeros(10)
print(np4)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [8]:
# Multidimensional Zeros
np5 = np.zeros((2,10))
print(np5)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [9]:
# Full
np6 = np.full((10), 6)
print(np6)

[6 6 6 6 6 6 6 6 6 6]


In [11]:
# Multidimensional Full
np7 = np.full((2,10), 6)
print(np7)

[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]


In [13]:
# convert python lists to np
my_lst = [1,2,3,4,5]
np8 = np.array(my_lst)
print(np8)
print(np8[0])

[1 2 3 4 5]
1


### Slicing Numpy Arrays

In [ ]:
np_1 = np.array([1,2,3,4,5,6,7,8,9])
print(np_1[1:5])
# to the end
print(np_1[3:])
# negative
print(np_1[-3:-1])


[2 3 4 5]
[4 5 6 7 8 9]
[7 8]


In [17]:
# Steps
print(np_1[1:5])
print(np_1[1:5:2])


[2 3 4 5]
[2 4]


In [18]:
# Steps on the entire array
print(np_1[::2])

[1 3 5 7 9]


In [20]:
# Slice a 2-d array
np_2 = np.array([
    [1,2,3,4,5], 
    [6,7,8,9,10]])
print(np_2[0:1, 1:3])
# Slicing from both rows
print(np_2[0:2, 1:3])

[[2 3]]
[[2 3]
 [7 8]]


### Numpy Universal Functions

In [26]:
np_3 = np.array([1,2,3,4,5,6,7,8,9])

In [27]:
# Square route of each element
print(np.sqrt(np_3))

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]


In [28]:
# Absolute value
np9 = np.array([-3,-2,-1,0,1,2,3,4,5,6,7,8,9])
print(np.absolute(np9))

[3 2 1 0 1 2 3 4 5 6 7 8 9]


In [29]:
# Exponentials
print(np.exp(np9))

[4.97870684e-02 1.35335283e-01 3.67879441e-01 1.00000000e+00
 2.71828183e+00 7.38905610e+00 2.00855369e+01 5.45981500e+01
 1.48413159e+02 4.03428793e+02 1.09663316e+03 2.98095799e+03
 8.10308393e+03]


In [30]:
# Min/Max
print(np.max(np9))
print(np.min(np9))

9
-3


In [31]:
# Sign -- positive or negative
print(np.sign(np9))

[-1 -1 -1  0  1  1  1  1  1  1  1  1  1]


In [33]:
# Trig sin cos log
print(np.sin(np9))
print(np.log(np9[4:]))

[-0.14112001 -0.90929743 -0.84147098  0.          0.84147098  0.90929743
  0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866   0.98935825
  0.41211849]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


### Copy Vs. View

In [40]:
np7 = np.array([1,2,3,4,5])

In [ ]:
# Create a view
np8 = np7.view()
print(f"The original np7 {np7}")
print(f"The original np8 {np8}")
np7[0] = 55
print(f"The change np7 {np7}")
print(f"The original np8 {np8}")   # a copy that still connected to the original

The original np7 [1 2 3 4 5]
The original np8 [1 2 3 4 5]
The change np7 [55  2  3  4  5]
The original np8 [55  2  3  4  5]


In [41]:
# Create a copy
np6 = np7.copy()
print(f"The original np7 {np7}")
print(f"The original np6 {np6}")
np7[0] = 55
print(f"The change np7 {np7}")
print(f"The original np6 {np6}")

The original np7 [1 2 3 4 5]
The original np6 [1 2 3 4 5]
The change np7 [55  2  3  4  5]
The original np6 [1 2 3 4 5]


### Shape and Reshape Numpy Arrays

In [43]:
np11 = np.array([[1,2,3,4,5,6], [7,8,9,10,11,12]])
print(np11.shape)

(2, 6)


In [45]:
np12 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
np13 = np12.reshape(3,4)
print(np13)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [46]:
np14 = np12.reshape(2,3,2)
print(np14)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [47]:
# flatten to 1-D
np5 = np14.reshape(-1)
print(np5)
print(np5.shape)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


### Iterating Through Numpy Arrays

In [49]:
np15 = np.array([[1,2,3,4,5], [6,7,8,9,10]])
for x in np15:
    #print rows
    print(x)
    for y in x:
        print(y)

[1 2 3 4 5]
1
2
3
4
5
[ 6  7  8  9 10]
6
7
8
9
10


In [56]:
np16 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in np16:
    #print(x)
    for y in x:
        #print(y)
        for z in y:
            print(z)


1
2
3
4
5
6
7
8
9
10
11
12


In [57]:
# np.nditer()
for x in np.nditer(np16):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


### Sorting Numpy Arrays

In [58]:
np17 = np.array([6,7,4,9,0,2,1])
print(np.sort(np17))

[0 1 2 4 6 7 9]


In [61]:
np18 = np.array(["Sara","Maha","Hoda","Tina"])
print(np.sort(np18))

['Hoda' 'Maha' 'Sara' 'Tina']


In [62]:
np9 = np.array([True, False, False, True])
print(np.sort(np9))

[False False  True  True]


In [63]:
np4 = np.array([[6,7,1,9], [8,3,5,0]])
print(np.sort(np4))

[[1 6 7 9]
 [0 3 5 8]]


### Searching Numpy Arrays

In [ ]:
np1 = np.array([1,2,3,4,5,6,7,8,9,10])
x = np.where(np1 == 3)
print(x)
print(x[0])

(array([2]),)
[2]


In [67]:
y = np.where(np1 %2 == 0)
print(y[0])

[1 3 5 7 9]


### Filtering Numpy Arrays

In [68]:
# Boolean index lists
np1 = np.array([1,2,3,4,5,6,7,8,9,10])
x = [True, True, False, False, False, False, False, False, False, False]
print(np1[x])


[1 2]


In [70]:
filtered = []
for thing in np1:
    if thing % 2 == 0:
        filtered.append(True)
    else:
        filtered.append(False)
print(filtered)
print(np1[filtered])

[False, True, False, True, False, True, False, True, False, True]
[ 2  4  6  8 10]


In [71]:
# Shortcut 
filtered = np1 % 2 == 0
print(filtered)
print(np1[filtered])

[False  True False  True False  True False  True False  True]
[ 2  4  6  8 10]


### Change specific element

In [12]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])

In [13]:
# Get specific elememt
a[1,5]

np.int64(13)

In [14]:
# Get specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
# Get Specific Column
a[:, 2]

array([ 3, 10])

In [16]:
b = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

In [17]:
b[0,1,1]

np.int64(4)

In [20]:
#replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


### ...

In [22]:
np.random.rand(4,2)

array([[0.15229767, 0.17474027],
       [0.40707869, 0.74703308],
       [0.42301984, 0.38750414],
       [0.40261601, 0.96372032]])

In [23]:
# Random integer values
np.random.randint(7, size=(3,3))

array([[4, 0, 6],
       [6, 3, 0],
       [5, 6, 2]], dtype=int32)

In [24]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr,4, axis=0)
print(r1)

[1 1 1 1 2 2 2 2 3 3 3 3]


In [28]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,4, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


### Linear Algebra

In [30]:
a = np.ones((2,3))
b =np.full((3,2), 2)
print(a)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [31]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

### Stats

In [33]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
np.min(stats, axis=0)

array([1, 2, 3])

In [35]:
np.max(stats)

np.int64(6)

### Reorganizing Arrays

In [38]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [39]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Load Data From File

In [42]:
filedata = np.genfromtxt(r'C:\Users\Nada\Downloads\data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


In [43]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])