In [3]:
import numpy as np

### Problem 1

In [5]:
# The identity matrix
np.identity(3) * 9

array([[9., 0., 0.],
       [0., 9., 0.],
       [0., 0., 9.]])

### Problem 2

In [12]:
a = np.ones((7,7))
a[1:6, 1:6] = 0
a[3,3] = 5
print(a)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 5. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


### Problem 3

In [ ]:
n = int(input("Enter a number: "))



### Problem 4

In [6]:
b = np.random.randint(0, 101, size=(5, 5))
print(b)
maximum = b.max(axis=1)
print(maximum)
sums = b.sum(axis=0)
print(sums)
mean = b.mean()
print(mean)
masking = np.where(b > 50, 1, 0)
print(masking)

[[56 18 90  0 59]
 [99 76 98 50 71]
 [99 50 91 13 95]
 [31  9 54 85  1]
 [44 77 79 88 18]]
[90 99 99 85 88]
[329 230 412 236 244]
58.04
[[1 0 1 0 1]
 [1 1 1 0 1]
 [1 0 1 0 1]
 [0 0 1 1 0]
 [0 1 1 1 0]]


### Problem 5